apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: backend-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

